name: Build and Test
on:
  push:
    tags:
      - v*
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v4
      with:
        go-version-file: go.mod

    - name: Build
      run: go build ./cmd/rollappd

    - name: Test
      run: go test ./...